import { StrictMode, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Connection, Keypair, LAMPORTS_PER_SOL, PublicKey } from '@solana/web3.js'
import { QRCodeSVG } from 'qrcode.react'
import './styles.css'

type Network = 'devnet' | 'testnet' | 'mainnet-beta'
const STORAGE_KEY = 'flux-wallet-vault-v1'
const endpoint = (network: Network) => network === 'devnet' ? 'https://api.devnet.solana.com' : network === 'testnet' ? 'https://api.testnet.solana.com' : 'https://api.mainnet-beta.solana.com'
const buffer = (value: Uint8Array) => value.slice().buffer
async function deriveKey(password: string, salt: Uint8Array) { const material = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveKey']); return crypto.subtle.deriveKey({ name: 'PBKDF2', salt: buffer(salt), iterations: 210_000, hash: 'SHA-256' }, material, { name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']) }
async function encryptSecret(secret: Uint8Array, password: string) { const salt = crypto.getRandomValues(new Uint8Array(16)); const iv = crypto.getRandomValues(new Uint8Array(12)); const key = await deriveKey(password, salt); const cipher = await crypto.subtle.encrypt({ name: 'AES-GCM', iv: buffer(iv) }, key, buffer(secret)); return JSON.stringify({ salt: Array.from(salt), iv: Array.from(iv), cipher: Array.from(new Uint8Array(cipher)) }) }
async function decryptSecret(payload: string, password: string) { const data = JSON.parse(payload); const key = await deriveKey(password, new Uint8Array(data.salt)); const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: buffer(new Uint8Array(data.iv)) }, key, buffer(new Uint8Array(data.cipher))); return new Uint8Array(plain) }
const short = (value: string) => `${value.slice(0, 5)}…${value.slice(-5)}`
const chains = [{ name: 'Ethereum', symbol: 'ETH', color: '#627eea' }, { name: 'BNB Chain', symbol: 'BNB', color: '#f3ba2f' }, { name: 'Solana', symbol: 'SOL', color: '#9af2c4' }, { name: 'Polygon', symbol: 'POL', color: '#8247e5' }]
const actions = [['↔', 'Swap'], ['⇄', 'Bridge'], ['↗', 'Send'], ['↓', 'Receive'], ['◉', 'Perps'], ['⌁', 'Lending'], ['GAS', 'Gas Deposit'], ['↺', 'Transactions'], ['▥', 'Market'], ['♢', 'Approvals'], ['✧', 'Rabby Points'], ['◌', 'Convert Dust']]
const websites = ['Polymarket', 'Predict Fun', 'Kalshi', 'OPINION', 'Limitless Exchange', 'Probable', 'Myriad']

function App() {
  const [network, setNetwork] = useState<Network>('devnet'); const [theme, setTheme] = useState<'dark'|'mono'>('dark'); const [tab, setTab] = useState<'home'|'receive'|'send'|'chains'>('home')
  const [vault, setVault] = useState<string | null>(() => localStorage.getItem(STORAGE_KEY)); const [keypair, setKeypair] = useState<Keypair | null>(null); const [password, setPassword] = useState(''); const [balance, setBalance] = useState<number | null>(null); const [notice, setNotice] = useState(''); const [recipient, setRecipient] = useState(''); const [amount, setAmount] = useState(''); const [history, setHistory] = useState<{signature:string; blockTime:number|null; err:unknown}[]>([]); const [tokens, setTokens] = useState<{mint:string; amount:string; decimals:number}[]>([])
  const address = keypair?.publicKey.toBase58() ?? ''; const connection = useMemo(() => new Connection(endpoint(network), 'confirmed'), [network])
  useEffect(() => { if (!keypair) return; connection.getBalance(keypair.publicKey).then(v => setBalance(v / LAMPORTS_PER_SOL)).catch(() => setNotice('RPC belum merespons.')); connection.getSignaturesForAddress(keypair.publicKey, { limit: 8 }).then(items => setHistory(items.map(item => ({ signature: item.signature, blockTime: item.blockTime ?? null, err: item.err })))).catch(() => setHistory([])); connection.getParsedTokenAccountsByOwner(keypair.publicKey, { programId: new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA') }).then(result => setTokens(result.value.filter(item => Number(item.account.data.parsed.info.tokenAmount.uiAmountString || 0) > 0).map(item => ({ mint: item.account.data.parsed.info.mint, amount: item.account.data.parsed.info.tokenAmount.uiAmountString, decimals: item.account.data.parsed.info.tokenAmount.decimals })))).catch(() => setTokens([])) }, [keypair, connection])
  const createWallet = async () => { if (password.length < 8) return setNotice('Gunakan password minimal 8 karakter.'); const kp = Keypair.generate(); localStorage.setItem(STORAGE_KEY, await encryptSecret(kp.secretKey, password)); setVault(localStorage.getItem(STORAGE_KEY)); setKeypair(kp); setPassword(''); setNotice('Wallet dibuat dan vault terenkripsi tersimpan lokal.') }
  const unlock = async () => { if (!vault) return; try { const bytes = await decryptSecret(vault, password); setKeypair(Keypair.fromSecretKey(bytes)); setPassword(''); setNotice('Vault terbuka. Private key tidak meninggalkan perangkat.'); } catch { setNotice('Password salah atau vault rusak.') } }
  const resetWallet = () => { if (!window.confirm('Reset wallet menghapus vault dan wallet lama dari perangkat ini. Lanjutkan?')) return; localStorage.removeItem(STORAGE_KEY); setVault(null); setKeypair(null); setPassword(''); setBalance(null); setNotice('Vault dihapus. Buat wallet baru atau pulihkan dari backup.') }
  const sendPreview = () => { try { new PublicKey(recipient); const lamports = Math.round(Number(amount) * LAMPORTS_PER_SOL); if (!Number.isFinite(lamports) || lamports <= 0) throw new Error(); setNotice(`Preview siap: ${amount} SOL + fee. Tidak ada transaksi yang dikirim.`) } catch { setNotice('Alamat atau jumlah tidak valid.') } }
  return <div className={`app ${theme}`}>
    <header><div className="brand"><span className="brand-mark">F</span><strong>FLUX</strong><em>WALLET</em></div><div className="header-tools"><span className="network-dot" /> <select value={network} onChange={e => setNetwork(e.target.value as Network)}><option value="devnet">Devnet</option><option value="testnet">Testnet</option><option value="mainnet-beta">Mainnet</option></select><button className="round-button">⋯</button><button className="round-button" onClick={() => setTheme(theme === 'dark' ? 'mono' : 'dark')}>⚙</button></div></header>
    <main>
      <section className="top-balance"><div><p className="muted-label">TOTAL BALANCE <span className="eye">◉</span></p><h1>{balance === null ? 'Rp 0.00' : `${balance.toFixed(4)} SOL`}</h1><p className="loss">−0.81% (−Rp689.80) <span>24h⌄</span></p></div><div className="wallet-pill">▣ &nbsp; {keypair ? short(address) : 'Connect wallet'} <span>›</span></div></section>
      {!vault ? <section className="panel onboarding"><p className="muted-label">FIRST FLIGHT</p><h2>Create your local vault</h2><p>Your keys stay encrypted on this device. No seed phrase or private key is sent to a server.</p><div className="form-row"><input type="password" placeholder="Vault password (8+ characters)" value={password} onChange={e => setPassword(e.target.value)} /><button onClick={createWallet}>Create wallet</button></div></section> : !keypair ? <section className="panel onboarding"><p className="muted-label">VAULT LOCKED</p><h2>Welcome back</h2><p>Unlock your vault to view balances. Forgot the password? Resetting permanently deletes this local vault.</p><div className="form-row"><input type="password" placeholder="Vault password" value={password} onChange={e => setPassword(e.target.value)} /><button onClick={unlock}>Unlock</button><button className="danger-button" onClick={resetWallet}>Reset</button></div></section> : <>
        {tab === 'home' && <><section className="action-grid">{actions.map(([icon, label]) => <button key={label} className="action-tile" onClick={() => label === 'Receive' ? setTab('receive') : label === 'Send' ? setTab('send') : setNotice(`${label} module is staged for the next secure integration.`)}><span className="action-icon">{icon}</span><strong>{label}</strong>{label === 'Transactions' && <b className="count">11</b>}</button>)}</section><section className="panel chain-strip"><div className="section-heading"><div><p className="muted-label">MULTI-CHAIN PORTFOLIO</p><h2>Networks</h2></div><button className="text-button" onClick={() => setTab('chains')}>Manage ›</button></div><div className="chain-list">{chains.map(chain => <div className="chain-chip" key={chain.name}><span style={{ background: chain.color }}>{chain.symbol[0]}</span><div><strong>{chain.name}</strong><small>{chain.symbol} · Coming soon</small></div></div>)}</div></section><section className="websites"><div className="section-heading"><h2>Websites</h2><span className="search-pill">⌕ Search website</span></div><div className="website-tabs"><b>All</b><span>DeFi</span><span>RWA</span><span>Perps</span><b>Predict</b><span>DEX</span><span>NFT</span></div>{websites.map((site, i) => <div className="website-row" key={site}><span className={`site-logo logo-${i}`}>{site[0]}</span><div><strong>{site}</strong><small>A curated Web3 website for your wallet experience...</small></div></div>)}</section></>}
        {tab === 'chains' && <section className="panel chain-detail"><p className="muted-label">SUPPORTED NETWORKS</p><h2>Multi-chain wallet</h2><p>Network connectors are staged safely. Balances and signing remain chain-specific and will be added one integration at a time.</p>{chains.map(chain => <div className="chain-detail-row" key={chain.name}><span style={{ background: chain.color }}>{chain.symbol[0]}</span><strong>{chain.name}</strong><small>Read-only integration planned</small></div>)}</section>}
        {tab === 'home' && <><section className="panel token-panel"><div className="section-heading"><div><p className="muted-label">SPL ASSETS</p><h2>Token balances</h2></div><span className="live-badge">READ ONLY</span></div>{tokens.length === 0 ? <p className="empty-history">No SPL tokens found on {network === 'mainnet-beta' ? 'Mainnet' : network}.</p> : tokens.slice(0, 8).map(token => <div className="token-row" key={token.mint}><span className="token-icon">◈</span><div><strong>{token.amount}</strong><small>{short(token.mint)} · {token.decimals} decimals</small></div></div>)}</section><section className="panel history-panel"><div className="section-heading"><div><p className="muted-label">ACTIVITY</p><h2>Transactions</h2></div><span className="live-badge">READ ONLY</span></div>{history.length === 0 ? <p className="empty-history">No transactions found on {network === 'mainnet-beta' ? 'Mainnet' : network}.</p> : history.map(item => <div className="history-row" key={item.signature}><span className="history-dot">↗</span><div><strong>{item.err ? 'Failed transaction' : 'Solana transaction'}</strong><small>{item.blockTime ? new Date(item.blockTime * 1000).toLocaleString() : 'Pending time'} · {short(item.signature)}</small></div><a href={`https://explorer.solana.com/tx/${item.signature}?cluster=${network === 'mainnet-beta' ? 'mainnet-beta' : network}`} target="_blank" rel="noreferrer">↗</a></div>)}</section></>}
        {tab === 'receive' && <section className="panel action-card"><p className="muted-label">RECEIVE SOL</p><h2>Your deposit address</h2><QRCodeSVG value={address} bgColor="transparent" fgColor="currentColor" size={180} /><code>{address}</code><button onClick={() => navigator.clipboard.writeText(address)}>Copy address</button></section>}
        {tab === 'send' && <section className="panel action-card"><p className="muted-label">SEND / PREVIEW ONLY</p><h2>Prepare a transfer</h2><p>Broadcast is disabled until security review is complete.</p><input placeholder="Recipient public address" value={recipient} onChange={e => setRecipient(e.target.value)} /><input placeholder="Amount in SOL" value={amount} onChange={e => setAmount(e.target.value)} /><button onClick={sendPreview}>Preview transfer</button></section>}
        <button className="lock-link" onClick={() => { setKeypair(null); setTab('home'); setNotice('Vault dikunci.') }}>Lock wallet</button>
      </>}
    </main><nav className="bottom-nav"><button className={tab === 'home' ? 'selected' : ''} onClick={() => setTab('home')}>⌂<span>Home</span></button><button>⌕<span>Discover</span></button><button onClick={() => setNotice('Search DApps akan tersedia setelah DApp browser ditambahkan.')}>Search Website<span /></button><button onClick={() => setNotice('Settings module akan tersedia pada tahap berikutnya.')}>⚙<span>Settings</span></button></nav>{notice && <div className="notice" role="status">{notice}</div>}
  </div>
}
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
